### ISSUE TITLE
Which database?

### ISSUE THREAD

**Issue by JamieAmstel** [OpenDevGroup/OpenDevManagement#4]
MySQL, Postgres and MongoDB? I would be interested in MongoDB, but only have experience with MySQL. Others?

**Comment by JustSteveKing** [comment]
I think when it comes to databases we need to go on what we need, not what we want to use. Does the data need to be relational? Are we going to have so many entries that none relational data is needed? It is easy to sit back and say let's use noSQL because it is the new thing, but we have to use what makes sense really.

From what I forsee this being needed / wanted for a MySQL database would be optimal. We need projects, members and task list all to be relational with each other, not just a single entry.

**Comment by jay-snee** [comment]
I propose we use Postgres, which is pretty similar to MySQL, but better in a number of ways (true boolean types spring to mind) and then if we need to, include a Redis NoSQL DB for caching and background jobs.

@JustSteveKing Just FYI, you _can_ use NoSQL DBs for relational data, you've just got to be a lot more careful about how you architect & manage it...

**Comment by JamieAmstel** [comment]
I'm happy to use Postgres, time to stop using tinyint I guess? :-)  I assume no one has any issues with using Postgres or other thoughts? if you do reopen
